/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpu.scheduling2;



import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elmnshawy
 */
public class Home extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrame
     */
    static List<Process> processes = new ArrayList<>();
    static DefaultTableModel model ;
    int quantumValue ;
    public Home(String cpu_Scheduling_Algorithm_Visualiser) {
        initComponents();
//        model = (DefaultTableModel) table.getModel();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // to close from exite
        setResizable(false); // Don't let anyone control the size
        setLocation(350, 100); //The window opens where I want
        
        setTitle("CPU Scheduling");
    }
//    public Home() {
//        initComponents();
//
//    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        excute = new javax.swing.JButton();
        add_process = new javax.swing.JButton();
        algorithme_type = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 222, 210));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Fax", 2, 24)); // NOI18N
        jLabel1.setText("CPU Scheduling Algorithm Visualizer");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name Process", "CPU-Time", "Wait Time", "Turnaround Time"
            }
        ));
        jScrollPane1.setViewportView(table);

        excute.setBackground(new java.awt.Color(42, 78, 103));
        excute.setForeground(new java.awt.Color(255, 255, 255));
        excute.setText("Excute");
        excute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excuteActionPerformed(evt);
            }
        });

        add_process.setBackground(new java.awt.Color(42, 78, 103));
        add_process.setForeground(new java.awt.Color(255, 255, 255));
        add_process.setText("Add process");
        add_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_processActionPerformed(evt);
            }
        });

        algorithme_type.setBackground(new java.awt.Color(42, 78, 103));
        algorithme_type.setForeground(new java.awt.Color(255, 255, 255));
        algorithme_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algorithme type", "FCFS", "SJF", "Priority", "Round Robin" }));
        algorithme_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithme_typeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(add_process, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(algorithme_type, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(excute, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_process, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algorithme_type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excute, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String getSelectedValue(JComboBox<String> comboBox) {
        String selectedValue = (String) comboBox.getSelectedItem();
        System.out.println("Selected value: " + selectedValue);
        return selectedValue;
    }
    
    
    private List<Integer> setPriorities() {
    int numberOfRows = table.getRowCount();
    if (numberOfRows == 0) {
        JOptionPane.showMessageDialog(null, "No rows in the table.", "Error", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    List<Integer> priorities = new ArrayList<>();

    for (int i = 0; i < numberOfRows; i++) {
        String processName = (String) model.getValueAt(i, 0);
        String priority = JOptionPane.showInputDialog(
            null,
            "Enter priority for process: " + processName,
            "Set Priority",
            JOptionPane.QUESTION_MESSAGE
        );

        if (priority != null && !priority.trim().isEmpty()) {
            try {
                int priorityValue = Integer.parseInt(priority);
                priorities.add(priorityValue);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid priority. Please enter a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
                i--;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Priority is required. Please enter a value.", "Error", JOptionPane.ERROR_MESSAGE);
            i--;
        }
    }

    JOptionPane.showMessageDialog(null, "All priorities have been set.", "Success", JOptionPane.INFORMATION_MESSAGE);
    return priorities;
}


    private void algorithme_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithme_typeActionPerformed
        if ("Round Robin".equals(algorithme_type.getSelectedItem())) {
        String quantum = javax.swing.JOptionPane.showInputDialog(this, "Enter quantum:", "Quantum Input", javax.swing.JOptionPane.PLAIN_MESSAGE);
        
        if (quantum != null && !quantum.isEmpty()) {
            try {
                quantumValue = Integer.parseInt(quantum);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Quantum set to: " + quantumValue, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid quantum value! Please enter a valid number.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantum input was canceled or left empty.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }
                
    if ("Priority".equals(algorithme_type.getSelectedItem())) {
        List<Integer> priorities = setPriorities();
        if (priorities != null) {
            System.out.println("Priorities: " + priorities);
        }
        for (int i = 0 ; i < priorities.size() ; i++){
            processes.get(i).setPriority(priorities.get(i));
        }
    }

    
    }//GEN-LAST:event_algorithme_typeActionPerformed

    private void add_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_processActionPerformed
        model = (DefaultTableModel) table.getModel();

        // Switch to the SearchResultsFrame
        Add_process Add_processFrame = new Add_process();
        Add_processFrame.setVisible(true);
        // Hide the current frame (optional)
//        setVisible(false);
    }//GEN-LAST:event_add_processActionPerformed

    private void excuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excuteActionPerformed
        // TODO add your handling code here:

        // FCFS, SJF, Priority, Round Robin
        
        String algorithm = algorithme_type.getSelectedItem().toString() ;
        
        if(algorithm == "FCFS"){
            //num_process[] , cpu_time[]
           processes  = Algorithmes.FCSA(processes);
           showProcessTable(processes);
        }
        else if (algorithm  == "SJF")
        {
            processes  = Algorithmes.SJF(processes);
            showProcessTable(processes);
        }
        else if (algorithm == "Priority"){
        
            processes  = Algorithmes.Priority(processes);
            showProcessTable(processes);

        }
        
        else if (algorithm == "Round Robin"){
        
            processes  = Algorithmes.RoundRobin(processes , quantumValue);
                        showProcessTable(processes);

        }
        else {
        
            // show messege to tell user select algorithm
            JOptionPane.showMessageDialog(null, "Please select an algorithm to proceed.", 
                                      "Algorithm Selection", JOptionPane.INFORMATION_MESSAGE);
        }
        
        

        
    }//GEN-LAST:event_excuteActionPerformed

//    private void filltable(int cpu_time[] , int Turnaround_time[]) {
//        for(int i=0 ; i<model.getRowCount() ; i++){
//            model.setValueAt(cpu_time[i], i, 2);
//            model.setValueAt(Turnaround_time[i], i, 3);
//            
//        }
//    }
    
    
    private static void showProcessTable(List<Process> processes) {
        
       
         for(int i=0 ; i < model.getRowCount() ; i++){
             model.setValueAt(processes.get(i).getWaitingTime(), i, 2);
             model.setValueAt(processes.get(i).getTurnaroundTime(), i, 3);   
             System.out.println(processes.get(i).getWaitingTime());
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home("CPU Scheduling Algorithm Visualiser").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_process;
    private javax.swing.JComboBox<String> algorithme_type;
    private javax.swing.JButton excute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
