/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cpu.scheduling2;

import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;


/**
 *
 * @author DELL
 */
public class Loading_frame extends javax.swing.JFrame {

    /**
     * Creates new form Loading_frame
     */

    public Loading_frame() {
    initComponents();
    
    this.setVisible(true);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // To close on exit
    setResizable(false); // Don't let anyone control the size
    setLocation(350, 150); // The window opens where I want
    
    setTitle("CPU Scheduling");
//
//    // Debug and load the image properly
String url = "F:\\EELU Matrial\\fiveth term\\OS\\Screenshot 2024-12-18 070802.png" ;
java.net.URL imgURL = Loading_frame.class.getResource(url);
if (imgURL != null) {
    jLabel2.setIcon(new javax.swing.ImageIcon(imgURL));
} else {
    System.err.println("Image not found! Check the path: /images/iconnn.png");
    jLabel2.setText("Image not found!");
}

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        myProgress = new JProgressBar();
        tage = new JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(189, 189, 189));

        myProgress.setForeground(new Color(42, 78, 103));

        tage.setFont(new Font("Segoe Print", 1, 36)); // NOI18N
        tage.setForeground(new Color(42, 78, 103));
        tage.setText("     %");

        jLabel1.setFont(new Font("Lucida Fax", 3, 36)); // NOI18N
        jLabel1.setText("CPU Scheduling");

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/images/iconnn.png"))); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(myProgress, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tage)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(tage, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(myProgress, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Loading_frame loding = new Loading_frame();
        loding.setVisible(true);
        try{
            for (int i = 0; i < 100; i++) {
                
 
            Thread.sleep(40);
            loding.myProgress.setValue(i);
            loding.tage.setText(Integer.valueOf(i)+"%");
            }
        }catch(Exception e)
        {
            
        }
        new Home("CPU Scheduling Algorithm Visualiser").setVisible(true);
//        setVisible(false);
        loding.dispose();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JProgressBar myProgress;
    private JLabel tage;
    // End of variables declaration//GEN-END:variables
}
